### ISSUE TITLE
Improve pages render method

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#925]
**Is your feature request related to a problem? Please describe.**

The current render method of the pages is pretty limited, some key improvements for Villain 2.0.0:

- [x] Optimizations.
- [x] Lazy load next pages.
- [ ] Fast transition + animations (See https://github.com/btzr-io/Villain/issues/926)
- [ ] Vertical / Horizontal direction ( See https://github.com/btzr-io/Villain/issues/889 )
- [ ]  Panel guided navigation ( https://github.com/btzr-io/Villain/issues/923 )
